A S You are in a forest
B M You are in a forest
C M You are in a forest
D E You find the lost treasure of the Whispering Wood within a hollow stump!
E M You are at the bottom of a steep hill
F M You are in a forest clearing
G M You are in a forest
H M You are in a forest glade
I M You are at the top of a steep hill
J M You are halfway down a steep hill
K M You are in a forest in a clearing full of tree stumps
L M You are in a forest
M M You are in a forest
N M You are in a forest in a rocky area
O M You are in a forest beside a pond
P M You are in a forest
Q M You are in a forest
R M You are in a forest
S M You are in a forest
